CI: try geocat benchmark

diff --git a/.github/workflows/build-and-validate-image.yml b/.github/workflows/build-and-validate-image.yml
--- a/.github/workflows/build-and-validate-image.yml
+++ b/.github/workflows/build-and-validate-image.yml
@@ -24,28 +24,132 @@ jobs:
 
   benchmark:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -el {0}
+    env:
+      CONDA_ENV_FILE: ./build_envs/asv-bench.yml
+      ASV_DIR: ./benchmarks
+
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v4
+      - name: Checkout
+        uses: actions/checkout@v4
         with:
-          python-version: "3.10"
-          cache: 'pip'
+          repository: bluesky/tiled
+          fetch-depth: 0
+      # - name: Checkout geocat-comp-asv
+      #   uses: actions/checkout@v4
+      #   with:
+      #     repository: NCAR/geocat-comp-asv
+      #     persist-credentials: false
+      #     fetch-depth: 0
+      #     ref: main
+      #     path: geocat-comp-asv
 
-      - name: Install
-        shell: bash -l {0}
+      - name: Setup Miniforge
+        uses: conda-incubator/setup-miniconda@v3
+        with:
+          miniforge-version: "latest"
+          activate-environment: asv-bench
+
+      - name: Get date
+        id: get-date
+        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
+        shell: bash
+
+      - name: Cache environment
+        uses: actions/cache@v4
+        with:
+          path: ${{ env.CONDA }}/envs
+          key:
+            conda-${{ runner.os }}--${{ runner.arch }}--${{
+            steps.get-date.outputs.today }}-${{
+            hashFiles('./build_envs/asv-bench.yml') }}-${{ env.CACHE_NUMBER}}
+        env:
+          # Increase this value to reset cache if the environment file has not changed
+          CACHE_NUMBER: 0
+        id: cache
+
+      - name: Update environment
+        run:
+          conda env update -n asv-bench -f
+          ./build_envs/asv-bench.yml
+        if: steps.cache.outputs.cache-hit != 'true'
+
+      - name: Conda list
         run: |
-          echo "Running!"
-          pip install requests_html
-          pip install libmambapy
-          pip install asv
-          asv machine --yes
-          asv run
-        # asv machine --yes
-        # asv continuous base pr --strict -e
-        # run: source continuous_integration/scripts/install.sh
+          conda info
+          conda list
 
+      # - name: Copy existing results
+      #   run: |
+      #     if [ -d "geocat-comp-asv/results" ]; then
+      #       cp -r geocat-comp-asv/results benchmarks/
+      #     fi
+
+      - name: Run benchmarks
+        id: benchmark
+        run: |
+          cd benchmarks
+          asv machine --machine GH-Actions --os ubuntu-latest --arch x64 --cpu "2-core unknown" --ram 7GB
+          asv run 
+      # v2023.02.0..main --skip-existing --parallel || true
+
+      # - name: Commit and push benchmark results
+      #   run: |
+      #     if [ -d "geocat-comp-asv/results" ]; then
+      #       rm -r geocat-comp-asv/results
+      #     fi
+      #     cp -r benchmarks/results/ geocat-comp-asv/
+      #     cd geocat-comp-asv
+      #     git config --local user.email "anissaz@ucar.edu"
+      #     git config --local user.name "anissa111"
+      #     git add results
+      #     git commit -m "[🤖] Update benchmark results"
+
+      # - name: Push to geocat-comp-asv
+      #   if: github.ref == 'refs/heads/main' && github.repository == 'NCAR/geocat-comp'
+      #   uses: ad-m/github-push-action@master
+      #   with:
+      #     github_token: ${{ secrets.COMP_ASV_PAT }}
+      #     branch: main
+      #     force: true
+      #     repository: NCAR/geocat-comp-asv
+      #     directory: geocat-comp-asv
+
+
+
+
+  # benchmark:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: mamba-org/setup-micromamba@v1
+  #       with:
+  #         micromamba-version: "latest"
+  #         init-shell: bash
+  #         post-cleanup: 'all'
+  #         auto-activate-base: true
+
+  #     # - name: Set up Python 3.10
+  #     #   uses: actions/setup-python@v4
+  #     #   with:
+  #     #     python-version: "3.10"
+  #     #     cache: 'pip'
+
+  #     - name: Install
+  #       # shell: bash -l {0}
+  #       run: |
+  #         echo "Running!"
+  #         pip install asv
+  #         asv machine --yes
+  #         asv run
+  #       # asv continuous base pr --strict -e
+  #       # run: source continuous_integration/scripts/install.sh
+
+
+      # wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
+      # bash ~/miniconda.sh -b -p $HOME/miniconda
       # - name: Install test requirements
       #   shell: bash -l {0}
       #   run: |
